name: Trigger auto deployment for scsubdir-6d4b1f7b

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/docker/**'
    - '.github/workflows/scsubdir-6d4b1f7b-AutoDeployTrigger-475c51d4-8d83-48a3-86ac-6ce1f24550d7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCSUBDIR6D4B1F7B_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCSUBDIR6D4B1F7B_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCSUBDIR6D4B1F7B_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerFilePath: /docker/dev.Dockerfile
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCSUBDIR6D4B1F7B_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCSUBDIR6D4B1F7B_REGISTRY_PASSWORD }}
          containerAppName: scsubdir-6d4b1f7b
          resourceGroup: cappsint-eastus-cni
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scsubdir-6d4b1f7b:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


