name: Trigger auto deployment for scsubdir-8b89adbd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/docker/**'
    - '.github/workflows/scsubdir-8b89adbd-AutoDeployTrigger-b6a1b266-635d-4ec4-b6f8-21c1d6de4307.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCSUBDIR8B89ADBD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCSUBDIR8B89ADBD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCSUBDIR8B89ADBD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerFilePath: /docker/dev.Dockerfile
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCSUBDIR8B89ADBD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCSUBDIR8B89ADBD_REGISTRY_PASSWORD }}
          containerAppName: scsubdir-8b89adbd
          resourceGroup: cappsint-eu2euap-rg
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scsubdir-8b89adbd:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


