name: Trigger auto deployment for scsubdir-5574fa9e

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/docker/**'
    - '.github/workflows/scsubdir-5574fa9e-AutoDeployTrigger-2a08ba6c-21fd-48db-b3b2-7ed793b2987a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCSUBDIR5574FA9E_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCSUBDIR5574FA9E_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCSUBDIR5574FA9E_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerFilePath: /docker/dev.Dockerfile
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCSUBDIR5574FA9E_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCSUBDIR5574FA9E_REGISTRY_PASSWORD }}
          containerAppName: scsubdir-5574fa9e
          resourceGroup: cappsint-eastasia-cni
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scsubdir-5574fa9e:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


