name: Trigger auto deployment for scsubdir-9ae03557

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/docker/**'
    - '.github/workflows/scsubdir-9ae03557-AutoDeployTrigger-682da1eb-6b03-4477-96e0-e26a7235d8f5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCSUBDIR9AE03557_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCSUBDIR9AE03557_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCSUBDIR9AE03557_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerFilePath: /docker/dev.Dockerfile
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCSUBDIR9AE03557_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCSUBDIR9AE03557_REGISTRY_PASSWORD }}
          containerAppName: scsubdir-9ae03557
          resourceGroup: cappsint-rg
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scsubdir-9ae03557:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


